"""Closed original retention source and reproducer grammars (Python 3.12 AST)."""

SOURCE_SHAPES = ('9186bd8253e3b55140e5f673154f3316a1b905b0aff0d1e5b33af1b377acf8e3', 'c7b0ea82cb784eb6467ff171aaae79d940c7f344b687e1c7c7fd7e222a50e2c5')

SCRIPT_SHAPES = ('2f0191b5d0c0218cc054f6428b2be2962fa8051b932cf1429e3cd3eed2f9c5ac', '72f312aa18f2f8d38a9e56f8a69458a28a137da88ce51e601d65b572a01eae19')

OLD_SCANNER_SHAPES = ('2a69847cbd85abe87246d68b1765d986e6ccf6db14a649c93f81e47ee7d62182',)

FIXED_WALK = "\ndef walk(value: Any, transcript: bool=False, key: str='') -> None:\n    if key in {'toolchain', 'producer', 'code_identity', 'tools_before', 'tools_after'} and (not transcript) and (not contains_transcript(value)):\n        return\n    if isinstance(value, dict):\n        transcript = transcript or explicit_transcript(value)\n        if transcript:\n            protect_values(value)\n        if isinstance(value.get('path'), str) and isinstance(value.get('sha256'), str):\n            path = Path(value['path'])\n            code_or_archive = path.suffix.lower() in {'.py', '.pyi', '.pyc', '.so', '.dylib', '.whl'} or path.name.endswith('.tar.gz')\n            kind = 'media' if value['sha256'] in digests else 'transcript' if transcript else 'media' if path.suffix.lower() in media_suffixes else 'review'\n            canonical_path = path if path.is_absolute() else (repo_root or directory) / path\n            public_code = repo_root is not None and any((canonical_path.resolve() == (repo_root / origin['git_path']).resolve() for origin in source_candidates.get(value['sha256'], [])))\n            if transcript or value['sha256'] in known:\n                add(canonical_path, kind if transcript else known[value['sha256']], value['sha256'], historical=True)\n            elif not public_code and kind != 'media' and (code_or_archive or value['sha256'] in source_candidates or value['sha256'] in source_snapshot_hashes):\n                candidate_path = path if path.is_absolute() else (repo_root or directory) / path\n                original_ref = {'path': str(candidate_path), 'sha256': value['sha256']}\n                ref = source_locators.get((str(candidate_path), value['sha256']), original_ref)\n                if ref is original_ref and str(candidate_path) in source_paths and (candidate_path == candidate_path.resolve()) and (not candidate_path.is_symlink()) and candidate_path.is_file() and (sha256(candidate_path) != value['sha256']):\n                    _require(re.fullmatch('[a-f0-9]{64}', value['sha256']), 'Historical source digest is invalid')\n                    unresolved_sources[str(candidate_path), value['sha256']] = {**original_ref, 'classification': 'UNCLASSIFIED', 'status': 'UNVERIFIED', 'current_ref': artifact_ref(candidate_path), 'reason': UNRESOLVED_REASON}\n                else:\n                    collect_candidate(candidate_path, original_ref, ref)\n            elif not public_code and path.is_absolute() and (path.resolve().is_relative_to(directory) or value['sha256'] in digests or transcript):\n                add(path, kind, value['sha256'], historical=True)\n            elif not public_code:\n                unfollowed.append({'path': value['path'], 'sha256': value['sha256'], 'reason': EXTERNAL_REASON})\n        for child_key, child in value.items():\n            walk(child, transcript, child_key)\n    elif isinstance(value, list):\n        for child in value:\n            walk(child, transcript)\n"

FIXED_CANDIDATE = "\ndef collect_candidate(candidate_path: Path, original_ref: dict[str, Any], ref: dict[str, Any]) -> None:\n    actual_path = _file(ref)\n    candidate_body = None\n    if actual_path.stat().st_size <= MAX_UNIT_BYTES:\n        try:\n            candidate_body = json.loads(actual_path.read_text())\n        except (ValueError, UnicodeDecodeError):\n            candidate_body = None\n    if contains_transcript(candidate_body):\n        add(candidate_path, 'transcript', ref['sha256'])\n    else:\n        candidate = {**ref, 'classification': 'UNCLASSIFIED', 'reason': CODE_REASON, 'matching_git_source_bytes': source_candidates.get(ref['sha256'], [])}\n        if ref is not original_ref:\n            candidate['original_reference'] = original_ref\n            candidate['preservation'] = PRESERVATION\n        public_candidates[str(actual_path)] = candidate\n        unfollowed.append({**ref, 'reason': candidate['reason']})\n"

INLINE_WALK = "\ndef walk(value: Any, transcript: bool=False, key: str='') -> None:\n    if key in {'toolchain', 'producer', 'code_identity', 'tools_before', 'tools_after'}:\n        return\n    if isinstance(value, dict):\n        transcript = transcript or (value.get('schema_version') == 'transcript/v1' and value.get('source_sha256') in digests)\n        if isinstance(value.get('path'), str) and isinstance(value.get('sha256'), str):\n            path = Path(value['path'])\n            code_or_archive = path.suffix.lower() in {'.py', '.pyi', '.pyc', '.so', '.dylib', '.whl'} or path.name.endswith('.tar.gz')\n            kind = 'media' if path.suffix.lower() in media_suffixes else 'transcript' if transcript and (not code_or_archive) else 'review'\n            canonical_path = path if path.is_absolute() else (repo_root or directory) / path\n            public_code = repo_root is not None and (any((canonical_path.resolve().is_relative_to(repo_root / name) for name in ('src', 'tests', 'examples', 'docs', '.github', 'schemas'))) or any((canonical_path.resolve() == (repo_root / origin['git_path']).resolve() for origin in source_candidates.get(value['sha256'], []))))\n            if not public_code and kind != 'media' and (value['sha256'] not in known) and (code_or_archive or value['sha256'] in source_candidates):\n                candidate_path = path if path.is_absolute() else (repo_root or directory) / path\n                ref = {'path': str(candidate_path), 'sha256': value['sha256']}\n                _file(ref)\n                candidate = {**ref, 'classification': 'UNCLASSIFIED', 'reason': CODE_REASON, 'matching_git_source_bytes': source_candidates.get(value['sha256'], [])}\n                public_candidates[str(candidate_path)] = candidate\n                unfollowed.append({**ref, 'reason': candidate['reason']})\n            elif not public_code and path.is_absolute() and (path.resolve().is_relative_to(directory) or value['sha256'] in digests or transcript):\n                add(path, kind, value['sha256'], historical=True)\n            elif not public_code:\n                unfollowed.append({'path': value['path'], 'sha256': value['sha256'], 'reason': EXTERNAL_REASON})\n        if transcript and isinstance(value.get('text'), str) and (len(value['text'].strip()) >= 40):\n            phrases.add(value['text'])\n        for child_key, child in value.items():\n            walk(child, transcript, child_key)\n    elif isinstance(value, list):\n        for child in value:\n            walk(child, transcript)\n    elif isinstance(value, str) and transcript and (key not in {'path', 'sha256', 'source_sha256', 'audio_sha256'}):\n        if len(value.strip()) >= 40 and (not Path(value).is_absolute()) and (not re.fullmatch('[a-f0-9]{64}', value)):\n            phrases.add(value)\n"

SCRIPT_SOURCE_PAIRS = (('2f0191b5d0c0218cc054f6428b2be2962fa8051b932cf1429e3cd3eed2f9c5ac', 'c7b0ea82cb784eb6467ff171aaae79d940c7f344b687e1c7c7fd7e222a50e2c5'), ('72f312aa18f2f8d38a9e56f8a69458a28a137da88ce51e601d65b572a01eae19', '9186bd8253e3b55140e5f673154f3316a1b905b0aff0d1e5b33af1b377acf8e3'))
