"""Real local identity controls; generated bytes are not media or approval."""
import ast
import hashlib
import inspect
import os

import pytest
from test_privacy_replay import ROOT, project

from talkcut import privacy_checks as privacy
from talkcut.project import TalkCutError, artifact_ref, atomic_json


def nested_collector(directory, entries=None):
    # Execute the actual nested function, not a rewritten model of the bug.
    tree = ast.parse(inspect.getsource(privacy.build_private_inventory))
    fn = next(item for item in tree.body[0].body if isinstance(item, ast.FunctionDef) and item.name == 'collect')
    ns = {**vars(privacy), 'directory': directory, 'entries': {} if entries is None else entries,
          'alias_observations': {}, 'unresolved': []}
    exec(compile(ast.Module(body=[fn], type_ignores=[]), privacy.__file__, 'exec'), ns)  # noqa: S102 -- trusted repository function, never artifact/producer code
    return ns


def chain(tmp_path):
    target = tmp_path / 'target.bin'
    target.write_bytes(b'Unclassified generated byte-identity test data')
    middle = tmp_path / 'middle'
    middle.symlink_to(target.name)
    link = tmp_path / 'alias'
    link.symlink_to(middle.name)
    return link, middle, target


@pytest.mark.parametrize('order', ['target_first', 'literal_first'])
def test_repeat_target_refs_and_literal_refs_keep_all_rows(tmp_path, order):
    link, middle, target = chain(tmp_path)
    ns = nested_collector(tmp_path)
    literal = hashlib.sha256(os.fsencode(os.readlink(link))).hexdigest()
    target_sha = artifact_ref(target)['sha256']
    if order == 'literal_first':
        ns['collect'](link, literal, literal_link=True)
    ns['collect'](link, target_sha)
    ns['collect'](link, target_sha)
    ns['collect'](link, literal, literal_link=True)
    rows = ns['entries']
    assert set(rows) == {str(link), str(middle), str(target)}
    assert rows[str(link)]['sha256'] == literal
    assert rows[str(target)]['sha256'] == target_sha
    assert all(row['classification'] == 'UNCLASSIFIED' for row in rows.values())


@pytest.mark.parametrize('damaged', ['target_bytes', 'target_identity', 'middle_literal', 'alias_removed', 'alias_regular'])
def test_changed_target_or_chain_rejected_after_first_reference(tmp_path, damaged):
    link, middle, target = chain(tmp_path)
    ns = nested_collector(tmp_path)
    digest = artifact_ref(target)['sha256']
    ns['collect'](link, digest)
    if damaged == 'target_bytes':
        target.write_bytes(b'Changed bytes')
    elif damaged == 'target_identity':
        replacement = tmp_path / 'same-content-other-target'
        replacement.write_bytes(target.read_bytes())
        middle.unlink()
        middle.symlink_to(replacement.name)
    elif damaged == 'middle_literal':
        middle.unlink()
        middle.symlink_to('./' + target.name)
    elif damaged == 'alias_removed':
        link.unlink()
    else:
        link.unlink()
        link.write_bytes(target.read_bytes())
    with pytest.raises(TalkCutError):
        ns['collect'](link, digest)


@pytest.mark.parametrize('literal', [False, True])
def test_first_reference_rejects_wrong_identity(tmp_path, literal):
    link, _, _ = chain(tmp_path)
    ns = nested_collector(tmp_path)
    with pytest.raises(TalkCutError):
        ns['collect'](link, '0' * 64, literal_link=literal)


def test_link_hash_does_not_serve_as_default_target_hash(tmp_path):
    link, _, _ = chain(tmp_path)
    digest = hashlib.sha256(os.fsencode(os.readlink(link))).hexdigest()
    ns = nested_collector(tmp_path)
    ns['collect'](link)
    with pytest.raises(TalkCutError, match='target bytes'):
        ns['collect'](link, digest)


@pytest.mark.parametrize('damage', ['cycle', 'dangling', 'directory'])
def test_unsupported_target_never_creates_completeness(tmp_path, damage):
    link, middle, target = chain(tmp_path)
    digest = artifact_ref(target)['sha256']
    middle.unlink()
    if damage == 'cycle':
        middle.symlink_to(link.name)
    elif damage == 'dangling':
        middle.symlink_to('absent')
    else:
        middle.symlink_to(tmp_path, target_is_directory=True)
    with pytest.raises(TalkCutError):
        nested_collector(tmp_path)['collect'](link, digest)


def test_directory_alias_then_dotdot_matches_kernel_target(tmp_path):
    near = tmp_path / 'near'
    away = tmp_path / 'away'
    near.mkdir(); away.mkdir(); (away / 'child').mkdir()
    correct = away / 'actual.bin'
    correct.write_bytes(b'Kernel-selected private fixture bytes')
    wrong = near / 'actual.bin'
    wrong.write_bytes(b'Lexically collapsed but wrong fixture bytes')
    (near / 'jump').symlink_to(away / 'child', target_is_directory=True)
    alias = near / 'alias'
    alias.symlink_to('jump/../actual.bin')
    ns = nested_collector(tmp_path)
    with pytest.raises(TalkCutError):
        ns['collect'](alias, artifact_ref(wrong)['sha256'])
    ns = nested_collector(tmp_path)
    ns['collect'](alias, artifact_ref(correct)['sha256'])
    assert {str(alias), str(near / 'jump'), str(correct)} == set(ns['entries'])
    assert str(wrong) not in ns['entries']


def test_existing_mandatory_private_target_role_is_conserved(tmp_path):
    link, _, target = chain(tmp_path)
    entry = {**artifact_ref(target), 'entry_type': 'file', 'classification': 'media', 'kind': 'media'}
    ns = nested_collector(tmp_path, {str(target): dict(entry)})
    ns['collect'](link, entry['sha256'])
    assert ns['entries'][str(target)] == entry
    assert all(row['classification'] != 'public_work' for row in ns['entries'].values())


def test_alias_rows_respect_original_finite_denominator_limit(tmp_path, monkeypatch):
    link, _, target = chain(tmp_path)
    monkeypatch.setattr(privacy, 'MAX_TASK_FILES', 2)
    with pytest.raises(TalkCutError, match='file-count bound'):
        nested_collector(tmp_path)['collect'](link, artifact_ref(target)['sha256'])


def test_complete_inventory_repeated_external_alias_refs(tmp_path):
    directory, sources = project(tmp_path)
    external = tmp_path / 'external'
    external.mkdir()
    link, middle, target = chain(external)
    declared = {'path': str(link), 'sha256': artifact_ref(target)['sha256']}
    atomic_json(directory / 'checkpoint.local.json', {'source_sha256': sources['screen'], 'references': [declared, declared]})
    inventory = privacy.build_private_inventory(directory, sources, ROOT)
    rows = {row['path']: row for row in inventory['entries']}
    assert {str(link), str(middle), str(target)} <= rows.keys()
    assert rows[str(link)]['entry_type'] == 'symlink'
    assert rows[str(target)]['entry_type'] == 'file'
    assert inventory['classification_status'] == 'UNVERIFIED'
    assert inventory['excluded_directories'] == [] and not inventory['unresolved']
    assert inventory['entry_count'] == len(inventory['entries'])


def test_literal_marker_cannot_be_injected_through_an_artifact_ref(tmp_path):
    directory, sources = project(tmp_path)
    external = tmp_path / 'external'
    external.mkdir()
    link, _, _ = chain(external)
    digest = hashlib.sha256(os.fsencode(os.readlink(link))).hexdigest()
    atomic_json(directory / 'checkpoint.local.json', {'source_sha256': sources['screen'], 'ref':
        {'path': str(link), 'sha256': digest, 'reference_type': 'symlink_literal'}})
    with pytest.raises(TalkCutError, match='target bytes'):
        privacy.build_private_inventory(directory, sources, ROOT)
